server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: xxx
    password: xxx
  redis:
    host: xxx
    port: 6379
    password: xxx
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: xxx
    username: hmdp
    password: xxx
    port: 5672
    virtual-host: /hmdp
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 5
          stateless: true
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.dianping.entity
logging:
  level:
    com.dianping: debug
leaf:
  name: seckill
  segment:
    enable: true
    url: jdbc:mysql://xxx:3306/leaf?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: xxx
    password: xxx

