---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Lenovo.
--- DateTime: 2024/2/6 19:52
---

-- 1. 参数列表
-- 1.1 优惠券id
local voucherId = ARGV[1]
-- 1.2 用户id
local userId = ARGV[2]


-- 2. key列表
-- 2.1 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2 订单key
local orderKey = 'seckill:order:' .. voucherId

-- 3. 业务
-- 3.1 判断库存是否充足
if tonumber(redis.call('GET', stockKey)) <= 0 then
    -- 库存不足，返回1
    return 1
end
-- 3.2 判断用户是否下单
if redis.call('sismember', orderKey, userId) == 1 then
    -- 已经下单，返回2
    return 2
end
-- 3.3 扣减库存
redis.call('incrby', stockKey, -1)
-- 3.4 添加用户
redis.call('sadd', orderKey, userId)
return 0